### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by Mathew4250** [manwhoami/MMeTokenDecrypt#7]
When running the program on 10.13.2 I get the following error and I'm not sure what it seems:

```
  File "MMeDecrypt.py", line 202, in <module>
    main()
  File "MMeDecrypt.py", line 106, in main
    dsid_bplist = data.fetchone()[5]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by manwhoami** [comment]
Hi, thanks for reporting this. Apple fixed the first bug in this script on macOS high Sierra. I have improved the error handling to return to the intended keychain query for any macOS > 10.13. This program still works on high Sierra, it will just use a different approach to obtaining the data.
